version: '2.1'

services:
  web-app:
    image: meta-tech-test_web-app
    build: ./
    env_file: .env
    environment: 
      DB_HOST: db
    volumes: 
      - ./:/var/www/site
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: